### ISSUE TITLE
安卓系统移动不好使

### ISSUE THREAD

**Issue by jiangshengxin** [euvl/vue-js-grid#18]
错误原因在文件188行:
https://github.com/euvl/vue-js-grid/blob/master/src/Grid.vue

代码应该如下:
var targetItem = {}
                    var itemLength = this.list.length;
                    for (var i = 0 ; i < itemLength ; i++) {
                        if (this.list[i].index === itemIndex) {
                            targetItem = this.list[i];
                        }

**Comment by euvl** [comment]
English pls, otherwise я тебе не понимаю 😄

**Comment by jiangshengxin** [comment]
Android mobile doesn't work,
The cause of error is Line 188:
//github.com/euvl/vue-js-grid/blob/master/src/Grid.vue

Should be replaced by:
`var targetItem = {} 
var itemLength = this.list.length; 
for（var i = 0; i <itemLength; i ++）{ 
if（this.list [i] .index === itemIndex）{ 
targetItem = this.list [i]; 
}`

**Comment by euvl** [comment]
Cool, feel free to create A PR
